server:
  port: 8082
spring:
  application:
    name: config-client
  cloud:
    config:
      name: springcloud-config
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: config-server
    bus:
      trace:        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
management:  endpoints:
    web:
      exposure:
        include: "*"