server:
  port: 8765
spring:
  application:
    name: turbine-server
turbine:
  app-config: zuul-server,config-client
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  combine-host-port: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/