server:
  port: 9411
spring:
  application:
    name: zipkin-server
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/