spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: ENC(2RenmNlNmZIlT9wAJmYGFw==)
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7